apiVersion: v1
kind: Service
metadata:
  name: react-svc
spec:
  type: {{ .Values.frontend.service.type }}
  selector:
    app: react
  ports:
    - port: {{ .Values.frontend.port }}
      targetPort: {{ .Values.frontend.port }}